// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package todo

// Injectors from wire.go:

func Initial() (UseCase, error) {
	todoRepository := NewRepository()
	todoUseCase := NewUseCase(todoRepository)
	return todoUseCase, nil
}
